-- ============================================
-- UCMS 统一证件验证中台系统 - 数据库表结构
-- ============================================

-- 1. 证件类型主表
CREATE TABLE IF NOT EXISTS UCMS_CERTIFICATE_TYPE (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cert_type_code VARCHAR(10) NOT NULL UNIQUE,
  cert_type_name VARCHAR(50) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(50),
  updated_by VARCHAR(50),
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- 1.1 证件类型主表索引
CREATE INDEX IF NOT EXISTS idx_ct_cert_type_code ON UCMS_CERTIFICATE_TYPE(cert_type_code);
CREATE INDEX IF NOT EXISTS idx_ct_status ON UCMS_CERTIFICATE_TYPE(status);
CREATE INDEX IF NOT EXISTS idx_ct_is_deleted ON UCMS_CERTIFICATE_TYPE(is_deleted);

-- 2. 字段库表（支持公共字段和自定义字段）
CREATE TABLE IF NOT EXISTS UCMS_FIELD_LIBRARY (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  field_name_cn VARCHAR(50) NOT NULL,
  field_name_en VARCHAR(50) NOT NULL,
  field_type VARCHAR(20) NOT NULL,
  field_data_type VARCHAR(20) NOT NULL,
  field_length INT,
  default_value VARCHAR(200),
  creator VARCHAR(50),
  description VARCHAR(200),
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- 2.1 字段库表索引
CREATE INDEX IF NOT EXISTS idx_fl_field_name_cn ON UCMS_FIELD_LIBRARY(field_name_cn);
CREATE INDEX IF NOT EXISTS idx_fl_field_name_en ON UCMS_FIELD_LIBRARY(field_name_en);
CREATE INDEX IF NOT EXISTS idx_fl_field_type ON UCMS_FIELD_LIBRARY(field_type);
CREATE INDEX IF NOT EXISTS idx_fl_status ON UCMS_FIELD_LIBRARY(status);
CREATE INDEX IF NOT EXISTS idx_fl_is_deleted ON UCMS_FIELD_LIBRARY(is_deleted);

-- 3. 证件类型字段配置表
CREATE TABLE IF NOT EXISTS UCMS_CERTIFICATE_TYPE_FIELD (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cert_type_code VARCHAR(10) NOT NULL,
  field_id BIGINT,
  field_name_en VARCHAR(50),
  field_name_cn VARCHAR(50),
  is_required TINYINT NOT NULL DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(50),
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- 3.1 证件类型字段配置表索引
CREATE INDEX IF NOT EXISTS idx_ctf_cert_type_code ON UCMS_CERTIFICATE_TYPE_FIELD(cert_type_code);
CREATE INDEX IF NOT EXISTS idx_ctf_field_id ON UCMS_CERTIFICATE_TYPE_FIELD(field_id);
CREATE INDEX IF NOT EXISTS idx_ctf_is_deleted ON UCMS_CERTIFICATE_TYPE_FIELD(is_deleted);

-- 4. 校验规则配置表
CREATE TABLE IF NOT EXISTS UCMS_VALIDATION_RULE_CONFIG (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  business_type VARCHAR(100),
  business_code VARCHAR(50) NOT NULL,
  channel_sub_type VARCHAR(50),
  allowed_cert_types TEXT,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(50),
  updated_by VARCHAR(50),
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- 4.1 校验规则配置表索引
CREATE INDEX IF NOT EXISTS idx_vrc_business_code ON UCMS_VALIDATION_RULE_CONFIG(business_code);
CREATE INDEX IF NOT EXISTS idx_vrc_channel_sub_type ON UCMS_VALIDATION_RULE_CONFIG(channel_sub_type);
CREATE INDEX IF NOT EXISTS idx_vrc_status ON UCMS_VALIDATION_RULE_CONFIG(status);
CREATE INDEX IF NOT EXISTS idx_vrc_is_deleted ON UCMS_VALIDATION_RULE_CONFIG(is_deleted);

-- 5. 校验规则明细表
CREATE TABLE IF NOT EXISTS UCMS_VALIDATION_RULE_ITEM (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  rule_id BIGINT NOT NULL,
  field_name VARCHAR(50) NOT NULL,
  validation_logic VARCHAR(50) NOT NULL,
  validation_value VARCHAR(100),
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- 5.1 校验规则明细表索引
CREATE INDEX IF NOT EXISTS idx_vri_rule_id ON UCMS_VALIDATION_RULE_ITEM(rule_id);
CREATE INDEX IF NOT EXISTS idx_vri_field_name ON UCMS_VALIDATION_RULE_ITEM(field_name);
CREATE INDEX IF NOT EXISTS idx_vri_is_deleted ON UCMS_VALIDATION_RULE_ITEM(is_deleted);

-- 6. 应用范围配置表
CREATE TABLE IF NOT EXISTS UCMS_SCOPE_CONFIG (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  business_channel VARCHAR(50),
  channel_sub_type VARCHAR(50),
  city VARCHAR(50),
  district VARCHAR(50),
  institution VARCHAR(100),
  allowed_cert_types TEXT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(50),
  updated_by VARCHAR(50),
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- 6.1 应用范围配置表索引
CREATE INDEX IF NOT EXISTS idx_sc_business_channel ON UCMS_SCOPE_CONFIG(business_channel);
CREATE INDEX IF NOT EXISTS idx_sc_channel_sub_type ON UCMS_SCOPE_CONFIG(channel_sub_type);
CREATE INDEX IF NOT EXISTS idx_sc_city ON UCMS_SCOPE_CONFIG(city);
CREATE INDEX IF NOT EXISTS idx_sc_district ON UCMS_SCOPE_CONFIG(district);
CREATE INDEX IF NOT EXISTS idx_sc_institution ON UCMS_SCOPE_CONFIG(institution);
CREATE INDEX IF NOT EXISTS idx_sc_status ON UCMS_SCOPE_CONFIG(status);
CREATE INDEX IF NOT EXISTS idx_sc_is_deleted ON UCMS_SCOPE_CONFIG(is_deleted);
